# This is a basic workflow to help you get started with Actions

name: Set secrets [DEVELOP]

# manually triggered
on: workflow_dispatch

jobs:          
    set-function-secrets:
        runs-on: ubuntu-latest

        steps:
            # Install firebase-tools which will be used to update the secrets
            - name: Install firebase-tools
              run: npm i -g firebase-tools@13.0.2

            # Update function secret using firebase-tools with the --force flag to trigger redeployment of functions
            - name: 'Set secrets'
              run: |
                echo "${{ secrets.TEST_VAR }}" | firebase --token "${{ secrets.FIREBASE_TOKEN }}" functions:secrets:set --force TEST_VAR --project action-test-2-e3b67
            

